name: Release to Maven Central

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major version'
        type: string
        required: true
      minor:
        description: 'Minor version'
        type: string
        required: true
      patch:
        description: 'Patch version'
        type: string
        required: true

env:
  NEW_VERSION: "${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"

jobs:
  release-to-maven-central:
    runs-on:
      - self-hosted
      - java
    steps:
      - uses: actions/checkout@v3
      - name: Setup git author information
        run: |
          git config user.name RCSBSystem
          git config user.email it@rcsb.org
      - name: Print out mvn, java and gpg versions
        run: |
          mvn --version
          java --version
          gpg --version
      - name: Set new version
        run: mvn versions:set -DnewVersion=$NEW_VERSION --no-transfer-progress
      - name: Commit and tag new version
        run: |
          git add pom.xml
          git commit -m "[automatic-release-to-maven-central] Updated version in pom.xml to $NEW_VERSION"
          git tag v$NEW_VERSION
      - name: Import gpg keys for signing artifacts in maven deploy phase
        # note that when importing private key gpg needs the passphrase. We grep it out from settings.xml
        run: |
          gpg --import ~/.secrets/maven_signing_public.gpg
          passphrase=$(grep gpg.passphrase ~/.secrets/settings.xml | sed "s/.*<.*>\(.*\)<.*>/\1/")
          gpg --pinentry-mode=loopback --passphrase  "$passphrase" --import ~/.secrets/maven_signing_private.gpg
      - name: Publish to ossrh (maven central) via maven deploy
        run: mvn -Prelease --batch-mode --errors -U clean deploy --no-transfer-progress
      - name: Increment version for next dev cycle
        run: |
          NEXT_PATCH=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.nextIncrementalVersion -q -DforceStdout --no-transfer-progress)
          mvn versions:set -DnewVersion="${{ inputs.major }}.${{ inputs.minor }}.$NEXT_PATCH-SNAPSHOT" -DallowSnapshots --no-transfer-progress
      - name: Commit new version for next dev cycle
        run: |
          git add pom.xml
          git commit -m "[actions] Next development cycle"
      - name: Push back to GitHub
        run: |
          git push --all
          git push --tags
  delay-for-maven-central:
    needs: release-to-maven-central
    runs-on:
      - self-hosted
      - java
    steps:
      # TODO This is not ideal, but needed because there are no options to wait in the maven plugin we use now (nexus-staging-maven-plugin), however
      # TODO in the central-publishing-maven-plugin it seems to be possible for maven to hold the deploy process until maven says it's ready, see https://central.sonatype.org/publish/publish-portal-maven/
      - name: Wait for rcsb-idmapper-client-java artifacts to appear in maven central
        # retry every 60 seconds x 180 times: 3 hours (after which it will fail)
        run: |
          MAVEN_URL="https://repo1.maven.org/maven2/org/rcsb/rcsb-idmapper-client/$NEW_VERSION/rcsb-idmapper-client-$NEW_VERSION.pom"
          echo "Will check the following URL via curl: $MAVEN_URL"
          curl --retry 180 --retry-all-errors --retry-delay 60 -f "$MAVEN_URL"